name: Update Conan Dependencies

on:
  workflow_dispatch:
    inputs:
      TASK_ID:
        description: "Task ID for the feature branch"
        required: true
        type: string

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MM_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Conan
        run: |
          pip install conan
          conan profile detect

      - name: Install Python dependencies
        run: |
          pip install requests
          pip install packaging

      - name: Run script to update dependencies
        id: update_deps
        run: python scripts/update_debug.py
        continue-on-error: true

      - name: Exit if no changes were made
        if: steps.update_deps.outcome != 'success'
        run: |
          echo "No changes detected, exiting workflow."
          exit 0

      - name: Create feature branch
        run: |
          BRANCH_NAME="feature/${{ inputs.TASK_ID }}-update-dependencies"
          git checkout -b "$BRANCH_NAME"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add conanfile.py
          git commit -m "${{ inputs.TASK_ID }}: Update dependencies to latest integration versions"
          git push origin HEAD

      - name: Create Pull Request feature -> main
        env:
          GITHUB_TOKEN: ${{ secrets.MM_GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="feature/${{ inputs.TASK_ID }}-update-dependencies"
          PR_TITLE="${{ inputs.TASK_ID }}: Update dependencies to latest integration versions"
          PR_BODY="This PR updates Conan dependencies to the latest available versions on the 'integration' channel."
          
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/pulls \
               -d "{\"title\":\"$PR_TITLE\", \"body\":\"$PR_BODY\", \"head\":\"$BRANCH_NAME\", \"base\":\"main\"}"

      - name: Create Pull Request main -> integration
        env:
          GITHUB_TOKEN: ${{ secrets.MM_GITHUB_TOKEN }}
        run: |
          PR_TITLE="${{ inputs.TASK_ID }}: Sync with integration"
          PR_BODY="This PR syncs main branch to integration branch."
          
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/pulls \
               -d "{\"title\":\"$PR_TITLE\", \"body\":\"$PR_BODY\", \"head\":\"main\", \"base\":\"integration\"}"
